# Basic reference: https://www.codeproject.com/Articles/1084565/Cplusplus-Continuous-Integration-Setup
dist: xenial
sudo: false
language: cpp
compiler: gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Release -- -j2

after_success:
  - echo "Success"
 
after_failure:
  - echo "Failed"

notifications:
  email:
    recipients:
      - anekde@gmail.com
      - dey.sumit.kr@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
